name: GroundInfrastructure Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get PySmartSkies
      uses: actions/checkout@v2
      with:
        repository: 'H3xept/CAELUS_SmartSkies'
        token: '${{ secrets.PAT }}'
        path: smartskies
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install ./smartskies
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest tests
      env:
        DIS_GRANT_TYPE: password
        DIS_CLIENT_ID: DMS
        DIS_USERNAME: ${{ secrets.dis_username }}
        DIS_PASSWORD: ${{ secrets.dis_password }}
        CVMS_PHONE: ${{ secrets.CVMS_PHONE}}
        CVMS_PASSWORD: ${{ secrets.CVMS_PASSWORD}}
        CVMS_DEVICE_ID: ${{ secrets.CVMS_DEVICE_ID}}